#!/bin/bash
#autousb

echo "welcome to use sutousb"
echo "do you want load usb(y/n)?"
read ans

if [ $ans = "Y" -o $ans = "y" ]
 then
  if [ -d "/mnt/usb" ]
  then 
  mount -t vfat /dev/sdb1 /mnt/usb
  else
  mkdir /mnt/usb
    if [ $? qe 0 ]
    then 
    echo "create /mnt/usb sucess"
    mount -t vfat /dev/sdb1 /mnt/usb
    fi
  fi
fi



